apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-wvisotkw
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/go-wvisotkw:e0cc035ffb2a963789dfe5cc213246bd1a7808d4@sha256:cd1988975ac82b66ffc8e8d91c9a40a907c75ef6364241058d94ed080ab196a4
          name: container-image
